title: "ZBlog"
baseline: "A Personal Programming Journal"
baseurl: https://zemian.github.io/
description: "This is Zemian Deng's personal programming blog."
author:
  name: Zemian Deng
  url: https://zemian.github.io/

# Do not generate multiple image sizes for favicon
metatags:
  favicon:
    enabled: false
